apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: stackhawk
inputs:
  token:
    required: true
  environment:
    required: true
  url:
    required: true
  app-id:
    required: true

runs:
  using: composite
  steps:
    - id: stackhawk
      name: stackhawk
      uses: docker://public.ecr.aws/l7o7z1g8/actions/stackhawk-dast-actions:main-a19ce057f432ef4a59bb5e8dc6fc84a0880b75f9
      shell: bash
      env:
        RUN_ID: ${{ cloudbees.run_id }}
        JOB_ID: ${{ job.id }}
        STEP_ID: ${{ step.internal.id }}
        DNS_URL: ${{ cloudbees.api.url }}
        JWT_TOKEN: ${{ cloudbees.api.token }} 
        CONFIG_JSON: '{\"metaInfo\":{\"url\":\"NA\",\"username\":\"NA\",\"password\":\"NA\",\"client_secret\":\"${{ inputs.token }}\",\"toolName\":\"stackhawk\",\"attributes\":{\"sub_attributes\":{\"stackhawk_context\":{\"environment\":\"${{ inputs.environment }}\",\"context\":{\"appId\":\"${{ inputs.app-id }}\",\"paths\":\"\"},\"url\":\"${{ inputs.url }}\"}}}},\"orchestratorInfo\":{\"assetType\":\"CORE\",\"assetIdentifier\":\"NA\",\"profileIdentifier\":\"NA\"},\"metaInformation\":{\"actor\":\"NA\",\"commit_id\":\"NA\",\"tenent_info\":\"NA\",\"scanner_type\":\"DAST\",\"pipeline_info\":{\"id\":\"04612\",\"name\":\"test_pipeline\",\"step_id\":\"04612_test_pipeline\"}}}'
      run: |
        set -x
        cd /app
        echo "RUN ID: ${{ cloudbees.run_id }}"
        echo "Job ID: ${{ job.id }}"
        echo "Step ID: ${{step.internal.id}}"
        echo "DNS URL: ${{ cloudbees.api.url }}"
        echo "JWT TOKEN: ${{ cloudbees.api.token }}"
        echo "CONFIG JSON: $CONFIG_JSON"
        /bin/bash -c "java $JAVA_OPTS -javaagent:/app/opentelemetry-javaagent.jar -jar /app/stackhawk.jar & while ! nc -z localhost 5001; do sleep 1; done && /app/orchestrator -scanConfig \"${CONFIG_JSON}\" execute-analyser && exit"


       
        
